# Generated by Django 5.1 on 2024-10-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_alter_segmentedimage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentedimage',
            old_name='id',
            new_name='uuid',
        ),
    ]
